### PR TITLE
Combine updates to several modules

### LINKED ISSUE #20: Check for queries that fail or return empty tables
We don't need this for the demo, but it will be something we will want to add shortly after we get the go-ahead to develop v1.0.

### PR DESCRIPTION
**Pull request by calebbraun**
This PR takes several unmerged updates to the package and combines them.

**New Modules**

- `agriculture.R` adds crop production, food consumption, and biomass production/consumption
- `emissions.R` contains CO2 and GHG emissions (converted to MTCO2e with AR4 or AR5 GWPs)
- `end_use.R` adds final energy by detailed end-use sector and fuel
- `landuse.R` adds land use by region
- `primary_energy.R` adds primary energy by fuel
- `water.R` adds water withdrawals, water consumption, water irrigation, and water witdrawals for electricity

**Changed Modules**

- `electricity.R` adds CCS to subsector
- `socioeconomics.R` can process 'counts' units

**Other Changes**

- No longer attempts to process queries with empty results
- Adds area and volume conversion capabilities
- Expands energy conversion to include TWh, Mboe, and Pcal

Resolves #20

### CODE REVIEW

File: R/units.R [hunk 1]
```diff
@@ -344,6 +351,61 @@ unitconv_mass <- function(iunit, ounit, inverse=FALSE)
...
+#' @keywords internal
+unitconv_area <- function(iunit, ounit, inverse=FALSE)
+{
+    unitasserts(iunit, ounit)
+
+    # Remove ^ symbol. Ex. m^2 becomes m2
+    iunit <- gsub('\\^', '', iunit)
+    ounit <- gsub('\\^', '', ounit)
+
+    # Replace m2 with meter2 (because of how extractunit works)
```
Comment (rplzzz) [inline R/units.R]: This is a good call.

File: R/units.R [hunk 2]
```diff
@@ -344,6 +351,61 @@ unitconv_mass <- function(iunit, ounit, inverse=FALSE)
...
+#'
+#' This function converts volume
+#'
+#' @param ounit Desired output unit.  If omitted, results will be returned with
+#' no unit conversion.
+#' @keywords internal
+unitconv_vol <- function(iunit, ounit, inverse=FALSE)
+{
+
+    # TODO: Make this a real function
```
Comment (rplzzz) [inline R/units.R]: It looks like this is not fully implemented.  Is that right?  If so, then we should probably issue a warning if it gets called so that users know they won't be getting the units they wanted.
